In [15]:
import numpy as np
import math
from itertools import combinations
from scipy.special import comb

In [ ]:
# Original R code for nchoosem:
# Permutation of O(n^4)
# Exact re-randomization matrix for small n choose m
library('gtools')
nchoosem = function(n,m) {
    c = choose(n,m)
    trt = combinations(n,m)
    Z = matrix(NA,c,n)
    for (i in 1:c) {
        Z[i,trt[i,]] = 1
        Z[i,-trt[i,]] = 0
    }
    return(Z)
}

In [74]:
def nchoosem(n, m): #(3,5)
    c = comb(m, n, exact=True) #int; number of combinations
    Z = np.zeros((c,n), dtype=int) #empty matrix
    combos = list(combinations(np.arange(1,m+1), n)) #list of combinations, trt will be the matrix
    print(combos)
    
    trt = np.zeros((c,n), dtype=int)
    print(trt)
    
    for i in np.arange(0, c):
        trt[i,] = combos[i]
    print(trt)
    
    for i in np.arange(0,c):
        Z[i,trt[i,]] = 1
        Z[i,-trt[i,]] = 0
    
    return Z

In [75]:
nchoosem(3,5)

[(1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 3, 4), (1, 3, 5), (1, 4, 5), (2, 3, 4), (2, 3, 5), (2, 4, 5), (3, 4, 5)]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 2 3]
 [1 2 4]
 [1 2 5]
 [1 3 4]
 [1 3 5]
 [1 4 5]
 [2 3 4]
 [2 3 5]
 [2 4 5]
 [3 4 5]]


IndexError: index 3 is out of bounds for axis 1 with size 3

In [40]:
# getting matrix of all combinations
x = list(combinations(np.arange(0,5), 3))
x

10


[(0, 1, 2),
 (0, 1, 3),
 (0, 1, 4),
 (0, 2, 3),
 (0, 2, 4),
 (0, 3, 4),
 (1, 2, 3),
 (1, 2, 4),
 (1, 3, 4),
 (2, 3, 4)]

In [32]:
trt = np.zeros((4,2), dtype=int)
print(trt)
for i in np.arange(0, 4):
    trt[i,] = np.random.choice(2, size=2, replace=False)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [35]:
test = np.zeros((4,2), dtype=int)
for i in np.arange(0, 4):
    test[i,] = [i*2, i*2]
test    

array([[0, 0],
       [2, 2],
       [4, 4],
       [6, 6]])

In [9]:
def tau_twoside_lower(n11, n10, n01, n00, alpha, Z_all):
    n = n11+n10+n01+n00
    m = n11+n10
    tau_obs = n11/m - n01/(n-m)
    ntau_obs = n*n11/m - n* n01/(n-m)
    tau_min = math.inf
    tau_max = -math.inf
    N_accept_min = np.nan
    N_accept_max = np.nan
    rand_test_total = 0
    
    for N11 in np.arange(0, min((n11+n01), n+ntau_obs)):
        tau_min_N11 = tau_lower_N11_twoside(n11, n10, n01, n00, N11, Z_all, alpha)
        # assumes that tau_lower_N11_twoside output is a dictionary
        rand_test_total = rand_test_total + tau_min_N11["rand_test_num"] 
        if(tau_min_N11["tau_min"] < tau_min):
            N_accept_min = tau_min_N11["N_accept_min"]
        if(tau_min_N11["tau_max"] > tau_max):
            N_accept_max = tau_min_N11["N_accept_max"]
        tau_min = min(tau_min, tau_min_N11["tau_min"])
        tau_max = max(tau_max, tau_min_N11["tau_max"])
    
    tau_lower = tau_min
    tau_upper = tau_max
    N_accept_lower = N_accept_min
    N_accept_upper = N_accept_max 
                      
    dict_output = {'tau_lower':tau_lower, 'N_accept_lower':N_accept_lower, 
                   'tau_upper':tau_upper, 'N_accept_upper':N_accept_upper,
                  'rand_test_total':rand_test_total}
    return dict_output